name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Python Linter (Flake8)
        uses: cclauss/python-lint-action@v1
        with:
          path: "backend"
          args: "--max-line-length=88"

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install JavaScript Linter
        run: npm install -g eslint

      - name: Lint Frontend
        run: eslint frontend --ext .js --ignore-pattern "node_modules/"

  build-and-push:
    name: Build & Push Docker Images
    needs: lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Backend Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/weather-backend:latest ./backend --build-arg WEATHER_API_KEY=${{ secrets.WEATHER_API_KEY }}
          docker push ${{ secrets.DOCKER_USERNAME }}/weather-backend:latest

      - name: Build and Push Frontend Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/weather-frontend:latest ./frontend
          docker push ${{ secrets.DOCKER_USERNAME }}/weather-frontend:latest
